# coding: utf-8

"""
    Splashify Pro Public API

    REST + GraphQL endpoints for sending WhatsApp messages, managing contacts, broadcasts, payment links, and more. SDKs for Node.js, Python, and PHP are auto-generated from this spec.

    The version of the OpenAPI document: 1.0
    Contact: support@splashifypro.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from splashifypro.api.messages_api import MessagesApi


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessagesApi()

    def tearDown(self) -> None:
        pass

    def test_public_message_post(self) -> None:
        """Test case for public_message_post

        Send a WhatsApp message
        """
        pass


if __name__ == '__main__':
    unittest.main()
