# coding: utf-8

"""
    Splashify Pro API

    REST endpoints for three product surfaces: 1. **Public API** under /public/* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. 3. **App API** under /app/* — the same surface the customer dashboard and the CLI/OpenClaw integrations use, authenticated with either an app session or an oc_live_… access token (`splashify auth login` / Settings → Developer → Access Tokens). Coverage here is partial — only endpoints touched by integrator reports are annotated so far, not the full surface. SDKs for Node.js, Python, and PHP are auto-generated from this spec.

    The version of the OpenAPI document: 1.0
    Contact: support@splashifypro.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from splashifypro.models.handlers_update_opt_out_error_request import HandlersUpdateOptOutErrorRequest

class TestHandlersUpdateOptOutErrorRequest(unittest.TestCase):
    """HandlersUpdateOptOutErrorRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandlersUpdateOptOutErrorRequest:
        """Test HandlersUpdateOptOutErrorRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandlersUpdateOptOutErrorRequest`
        """
        model = HandlersUpdateOptOutErrorRequest()
        if include_optional:
            return HandlersUpdateOptOutErrorRequest(
                enabled = True
            )
        else:
            return HandlersUpdateOptOutErrorRequest(
        )
        """

    def testHandlersUpdateOptOutErrorRequest(self):
        """Test HandlersUpdateOptOutErrorRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
