# coding: utf-8

"""
    Splashify Pro Public API

    REST + GraphQL endpoints for sending WhatsApp messages, managing contacts, broadcasts, payment links, and more. SDKs for Node.js, Python, and PHP are auto-generated from this spec.

    The version of the OpenAPI document: 1.0
    Contact: support@splashifypro.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from splashifypro.api.conversations_api import ConversationsApi


class TestConversationsApi(unittest.TestCase):
    """ConversationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConversationsApi()

    def tearDown(self) -> None:
        pass

    def test_public_assignment_post(self) -> None:
        """Test case for public_assignment_post

        Assign a chat to a team member
        """
        pass


if __name__ == '__main__':
    unittest.main()
