# coding: utf-8

"""
    Splashify Pro Public API

    REST + GraphQL endpoints for sending WhatsApp messages, managing contacts, broadcasts, payment links, and more. SDKs for Node.js, Python, and PHP are auto-generated from this spec.

    The version of the OpenAPI document: 1.0
    Contact: support@splashifypro.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from splashifypro.api.meta_conversions_api import MetaConversionsApi


class TestMetaConversionsApi(unittest.TestCase):
    """MetaConversionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MetaConversionsApi()

    def tearDown(self) -> None:
        pass

    def test_public_capi_send_event_post(self) -> None:
        """Test case for public_capi_send_event_post

        Send a Meta Conversion API event
        """
        pass


if __name__ == '__main__':
    unittest.main()
