# coding: utf-8

"""
    Splashify Pro Public API

    REST + GraphQL endpoints for sending WhatsApp messages, managing contacts, broadcasts, payment links, and more. SDKs for Node.js, Python, and PHP are auto-generated from this spec.

    The version of the OpenAPI document: 1.0
    Contact: support@splashifypro.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from splashifypro.api.contacts_api import ContactsApi


class TestContactsApi(unittest.TestCase):
    """ContactsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContactsApi()

    def tearDown(self) -> None:
        pass

    def test_public_apis_users_post(self) -> None:
        """Test case for public_apis_users_post

        List contacts (paginated, filterable)
        """
        pass


if __name__ == '__main__':
    unittest.main()
