# coding: utf-8

"""
    Splashify Pro API

    REST endpoints for two product surfaces: 1. **Public API** under /public/* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. SDKs for Node.js, Python, and PHP are auto-generated from this spec.

    The version of the OpenAPI document: 1.0
    Contact: support@splashifypro.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from splashifypro.api.partner_email_stats_api import PartnerEmailStatsApi


class TestPartnerEmailStatsApi(unittest.TestCase):
    """PartnerEmailStatsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PartnerEmailStatsApi()

    def tearDown(self) -> None:
        pass

    def test_partner_email_quotas_get(self) -> None:
        """Test case for partner_email_quotas_get

        Get sending quotas
        """
        pass

    def test_partner_email_stats_get(self) -> None:
        """Test case for partner_email_stats_get

        Get sending statistics
        """
        pass


if __name__ == '__main__':
    unittest.main()
