# coding: utf-8

"""
    Splashify Pro Public API

    REST + GraphQL endpoints for sending WhatsApp messages, managing contacts, broadcasts, payment links, and more. SDKs for Node.js, Python, and PHP are auto-generated from this spec.

    The version of the OpenAPI document: 1.0
    Contact: support@splashifypro.in
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from splashifypro.api.email_api import EmailApi


class TestEmailApi(unittest.TestCase):
    """EmailApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmailApi()

    def tearDown(self) -> None:
        pass

    def test_public_email_send_post(self) -> None:
        """Test case for public_email_send_post

        Send a transactional email
        """
        pass

    def test_public_email_send_template_post(self) -> None:
        """Test case for public_email_send_template_post

        Send a templated email
        """
        pass

    def test_public_email_status_message_id_get(self) -> None:
        """Test case for public_email_status_message_id_get

        Get email delivery status
        """
        pass


if __name__ == '__main__':
    unittest.main()
